name: Update status

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "7 */8 * * *"

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.3

      - name: setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x

      - name: get omg.lol status
        id: extract
        uses: lucasmelin/omg.lol-gh-status-sync-action@v1.0.2
        with:
          omg_lol_user: andypiper
          github_token: ${{ secrets.PERSONAL_USER_TOKEN }}
